base_url = "https://blog.wipeseals.me"
theme = "terminimal"
compile_sass = true
build_search_index = true
description = "test description"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true


[extra]
show_only_description = true
accent_color = "blue"
background_color = "dark"
logo_text = "blog.wipeseals.me"
logo_home_link = "/"
author = "wipeseals"
copyright_html = "Copyright &copy; 2024 wipeseals"
menu_items = [
    { name = "blog", url = "$BASE_URL" },

    { name = "tags", url = "$BASE_URL/tags" },
    { name = "archive", url = "$BASE_URL/archive" },

    { name = "about me", url = "https://wipeseals.me" },
    { name = "github", url = "https://github.com/wipeseals", newtab = true },
]
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
default_language = "ja"
use_full_hack_font = true
favicon = "/favicon.ico"
favicon_mimetype = "image/x-icon"
page_titles = "combined"
