base_url = "https://blog.wipeseals.me"
title = "blog.wipeseals.me"
description = "Miscellaneous logs..."
author = "wipeseals"
default_language = "ja"
generate_feeds = true
feed_filenames = ["atom.xml"]
theme = "kita"
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
math = true
mermaid = true
comment = false
social_image = "icon.png"

[extra.profile]
name = "wipeseals"
bio = "I'm interested in the intersection of hardware, software, and system reliability."
avatar_url = "icon.png"

[[extra.profile.social]]
name = "github"
url = "https://github.com/wipeseals"

[[extra.profile.social]]
name = "bluesky"
url = "https://bsky.app/profile/wipeseals.me"

[[extra.profile.social]]
name = "gmail"
url = "mailto:wipeseals+contact@example.com"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[[extra.menu]]
name = "blog"
url = "$BASE_URL"

[[extra.menu]]
name = "tags"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "work"
url = "$BASE_URL/work"

[[extra.menu]]
name = "about"
url = "https://wipeseals.me"

[[extra.menu]]
name = "github"
url = "https://github.com/wipeseals"

[extra.footer]
since = 2024
